### ISSUE TITLE
Official Checklist

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Screna#6]
**Performance**
- [x] Improve efficiency of Recorder algorithm
- [x] Improve Audio+Video sync
- [x] Fix Audio+Video Duration
- [x] Fix Wasapi Loopback sync issues

**API**
- [x] Improve FFMpegVideoWriter
- [x] Add EncodedAudioProvider
- [x] CroppedImageProvider
- [x] RotatedImageProvider
